global:
  image:
    repository: weaveworks/scope
    tag: 1.10.1
    pullPolicy: "IfNotPresent"
  service:
    port: 80
    type: "ClusterIP"
weave-scope-frontend:
  enabled: true
  ingress:
    enabled: enabled
    name: ingress-weave-scope
    host: gabriel
    path: "/weavescope"
    className: ""
    extraPaths: ""
    annotations:
weave-scope-agent:
  enabled: true
  dockerBridge: "docker0"
  scopeFrontendAddr: ""
  probeToken: ""
  rbac:
    create: true
  readOnly: false
  serviceAccount:
    create: true
