apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd  
spec:
  generators:
  - git:
      repoURL: https://github.com/gabrielfsousa/infra001.git 
      revision: HEAD
      files:
        - path: "grafana/*/cluster.yaml"
  template:
    metadata:
      name: '{{cluster}}-grafana'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - {{cluster}}/v.yaml
        repoURL: https://github.com/grafana/helm-charts.git 
        targetRevision: HEAD
        path: "charts/grafana"
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'  

      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true     
