limitNamespace: false
replicaCount: 1
image:
  repository: ghcr.io/benc-uk/kubeview
  tag: 0.1.31
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
  tls: []
  className: ""
loadBalancer:
  IP: ""
  enabled: true
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
